# Generated by Django 5.1.4 on 2026-01-29 12:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ad_type', models.CharField(choices=[('VIDEO', 'Video Ad'), ('PICTURE', 'Picture Ad')], max_length=10)),
                ('media_file', models.FileField(upload_to='ads/')),
                ('caption', models.TextField(blank=True, max_length=500)),
                ('external_link', models.URLField(blank=True, help_text='Link to open when ad is clicked')),
                ('slot_position', models.IntegerField(choices=[(1, 'Slot 1 - Video'), (2, 'Slot 2 - Video'), (3, 'Slot 3 - Picture'), (4, 'Slot 4 - Picture')], unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['slot_position'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FantasyLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('telegram_handle', models.CharField(blank=True, max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('rank', models.PositiveIntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('competition', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['match_date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('CAMPUS', 'Campus'), ('TECH', 'Tech'), ('SPORTS', 'Sports'), ('ANNOUNCEMENT', 'Announcement')], default='GENERAL', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField()),
                ('away_score', models.PositiveIntegerField()),
                ('summary', models.TextField(blank=True, help_text='Match summary or highlights')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='bot.fixture')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(help_text='Telegram user ID', unique=True)),
                ('name', models.CharField(help_text='Business/Provider name', max_length=200)),
                ('description', models.TextField(help_text='Short description of services', max_length=500)),
                ('keywords', models.JSONField(default=list, help_text="List of keywords for search (e.g., ['lash', 'makeup', 'beauty'])")),
                ('plan_type', models.CharField(choices=[('BASIC', 'Basic - ₦1,500'), ('VERIFIED', 'Verified - ₦3,000'), ('PREMIUM', 'Premium - ₦5,000')], default='BASIC', max_length=10)),
                ('badge_type', models.CharField(choices=[('NONE', 'No Badge'), ('VERIFIED', '✅ Verified'), ('PREMIUM', '⭐ Premium')], default='NONE', max_length=10)),
                ('is_verified', models.BooleanField(default=False, help_text='Has been verified by admin')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('telegram_handle', models.CharField(blank=True, help_text='@username', max_length=100)),
                ('instagram_handle', models.CharField(blank=True, help_text='@username', max_length=100)),
                ('hall_of_residence', models.CharField(blank=True, help_text='Hall of residence (Premium only)', max_length=100)),
                ('catalogue', models.FileField(blank=True, help_text='PDF catalogue/portfolio', null=True, upload_to='catalogues/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('is_approved', models.BooleanField(default=False, help_text='Approved by admin to appear in search')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='bot.category')),
            ],
            options={
                'ordering': ['-plan_type', '-created_at'],
            },
        ),
    ]
