# Generated by Django 5.1.4 on 2026-02-10 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.IntegerField(help_text='Amount in kobo')),
                ('plan_type', models.CharField(choices=[('BASIC', 'Basic - ₦1,500'), ('VERIFIED', 'Verified - ₦3,000'), ('PREMIUM', 'Premium - ₦5,000')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned')], default='PENDING', max_length=10)),
                ('authorization_url', models.URLField(blank=True)),
                ('paystack_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bot.serviceprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
